version: '3.9'

services:
  database:
    build: ./mysql-image
    environment:
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: News_Db
       MYSQL_USER: user
       MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  
  backend:
    build: ./backend-image
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build: ./frontend-image
    ports:
      - "80:80"
    depends_on:
      - backend